# Generated by Django 3.1.7 on 2021-04-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='itemImages/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_review',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
