# Generated by Django 3.1.7 on 2021-04-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
