# Generated by Django 3.1.7 on 2021-04-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order_amount',
            field=models.IntegerField(null=True),
        ),
    ]
